#!/usr/bin/env python3
from dpp_jump_compiler import lookup_opcode
from os import sys

if len(sys.argv) < 3:
    print("Usage: {} <input_file_name> <opcode>".format(sys.argv[0]))
    exit(-1)
    
with open(sys.argv[1], 'r') as f:
    lookup_opcode(sys.argv[1], int(sys.argv[2], 16))