include(UseD)
add_d_conditions(VERSION GL_AllowDeprecated default Have_gamebean_emu Have_silly Have_bindbc_opengl Have_bindbc_sdl Have_commandr Have_bindbc_loader DEBUG )
include_directories(/home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/)
include_directories(/home/xdrie/.dub/packages/silly-1.1.1/silly)
include_directories(/home/xdrie/.dub/packages/bindbc-opengl-1.0.0/bindbc-opengl/source/)
include_directories(/home/xdrie/.dub/packages/bindbc-loader-1.0.1/bindbc-loader/source/)
include_directories(/home/xdrie/.dub/packages/bindbc-sdl-1.0.1/bindbc-sdl/source/)
include_directories(/home/xdrie/.dub/packages/commandr-0.2.0/commandr/source/)
add_executable(gamebean-emu 
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/app.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/diag/cputrace.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/diag/logger.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/host/sdl.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/hw/apu/apu.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/hw/apu/audiobuffer.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/hw/apu/channel.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/hw/apu/channels/noise-channel.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/hw/apu/channels/tone-channel.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/hw/apu/channels/wave-channel.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/hw/apu/fifo.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/hw/apu/package.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/hw/cpu/arm7tdmi.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/hw/cpu/exception.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/hw/cpu/mode.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/hw/cpu/package.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/hw/cpu/state.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/hw/dma.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/hw/gba.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/hw/interrupts.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/hw/keyinput.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/hw/memory/memory-mapped-io.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/hw/memory/memory.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/hw/memory/package.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/hw/ppu/background.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/hw/ppu/canvas.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/hw/ppu/layer/background-layer.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/hw/ppu/layer/layer.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/hw/ppu/layer/package.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/hw/ppu/lcd.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/hw/ppu/package.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/hw/ppu/palette.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/hw/ppu/pixel.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/hw/ppu/point.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/hw/timers.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/jumptable_arm.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/jumptable_thumb.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/logger.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/save/backups/backup.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/save/backups/flash.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/save/backups/package.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/save/package.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/save/save_detector.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/save/savetype.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/save/savetype_factory.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/scheduler.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/tests/rom_tests.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/util/ringbuffer.d
    /home/xdrie/Dev/Git/GameBeanAdvance/src/emu/source/util/util.d
    /home/xdrie/.dub/packages/silly-1.1.1/silly/silly.d
)
target_link_libraries(gamebean-emu bindbc-loader bindbc-opengl bindbc-sdl commandr dl)
set_target_properties(gamebean-emu PROPERTIES TEXT_INCLUDE_DIRECTORIES "")
