#!/usr/bin/env python3
from cpp_jump_compiler import compile
from os import sys

if len(sys.argv) < 2:
    print("Usage: python {} <file_name>".format(sys.argv[0]))
    exit(-1)
    
with open(sys.argv[1], 'r') as f:
    compile(sys.argv[1])